name: Train Data Scheduler and Committer

# Controls when the workflow will run
on:
  schedule:
    # Runs every 10 minutes (using cron syntax)
    - cron: '*/10 * * * *'
  # Allows manual triggering from the Actions tab in the GitHub UI
  workflow_dispatch:

jobs:
  update-train-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Required to fetch the full history so fetch_data.py can read data.json
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Python data fetch script
        run: python fetch_data.py

      - name: Check for changes
        id: git_status
        run: echo "changes=$(git status --porcelain | wc -l)" >> $GITHUB_OUTPUT

      - name: Commit and Push changes
        if: steps.git_status.outputs.changes != '0'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Data Update: New Darwin snapshot added"
          branch: main
